import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "AI Shopping Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="dracula" lang="en">
      <body
        className={`${roboto.className} flex justify-center items-start min-h-screen`}
      >
        <div className="flex flex-col justify-between h-[852px] w-[393px] border p-4 ">
          {children}
        </div>
      </body>
    </html>
  );
}
